### ISSUE TITLE
" is not recognized as an internal or external command, operable program or batch file"

### ISSUE THREAD

**Issue by Redax88** [Zhongli0401/korepi-tools#1]
when i tried to run the  "first time setup" . this error came up in the cmd. How to fix this? 
![image](https://github.com/Zhongli0401/korepi-tools/assets/112399500/4a4351a9-dd3a-45d0-851b-250631e18b79)

**Comment by Zhongli0401** [comment]
erm wtf which one you used ?

**Comment by Zhongli0401** [comment]
strange the version from github somehow got messed up but the file are same how tf is this possible lmao

**Comment by Gorggis86** [comment]
i got same issue please any ways to fix this error ?!

**Comment by Zhongli0401** [comment]
its fixed now
use the latest rel 

https://github.com/Zhongli0401/korepi-tools/releases/tag/0.0.8

**Comment by Zhongli0401** [comment]
ok i will be closing this issue under 6 hours if the problem is fixed please comment here or if u have any other issues

**Comment by Gorggis86** [comment]
> ok i will be closing this issue under 6 hours if the problem is fixed please comment here or if u have any other issues

Active code page: 65001

what dose it mean ?! i don't get any security warning after running first-time-setup.bat

**Comment by Gorggis86** [comment]
> > ok i will be closing this issue under 6 hours if the problem is fixed please comment here or if u have any other issues
> 
> Active code page: 65001
> 
> what dose it mean ?! i don't get any security warning after running first-time-setup.bat

**Comment by Gorggis86** [comment]
also when i run first-time-setup.bat after getting hwid it just opens up another cmd and after that opens krp its self to get hwid again nothin about entering hwid into cmd or any security warning

**Comment by Zhongli0401** [comment]
what everything is working fine here i checked all the files  3 to 4 time can u make a different folder and try in that

**Comment by Gorggis86** [comment]
> what everything is working fine here i checked all the files 3 to 4 time can u make a different folder and try in that

check discord i did sent you picture of problem

**Comment by Zhongli0401** [comment]
fixed

**Comment by Redax88** [comment]
ok. i can confirm it does kinda work with a few issues on my end. 
i click the "first time setup". all the cmd window came out including the cmd stating the key expires at this date etc2 but the genshin didn't launch. all the window close with nothing happen. i have to manually edit the host file and paste the address from fadillz  :
```
127.0.0.1 ghp.535888.xyz
127.0.0.1 md5c.535888.xyz
```
then only everything goes well. the cmd window came out, ask me the genshin.exe location and the game starts. 
ive probably missed some steps or tutorial video but alas. Thanks for the fix.

**Comment by Zhongli0401** [comment]
> ok. i can confirm it does kinda work with a few issues on my end. i click the "first time setup". all the cmd window came out including the cmd stating the key expires at this date etc2 but the Henshin didn't launch. all the window close with nothing happen. i have to manually edit the host file and paste the address from fadillz :
> 
> ```
> 127.0.0.1 ghp.535888.xyz
> 127.0.0.1 md5c.535888.xyz
> ```
> 
> then only everything goes well. the cmd window came out, ask me the Henshin.exe location and the game starts. ive probably missed some steps or tutorial video but alas. Thanks for the fix.

korepi issue if the game doesnot launch

**Comment by Redax88** [comment]
well it works now. Thanks for the response. cheers
